ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_id CASCADE;
ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS role_id CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.role CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
