version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Бэкенд на Rust
  backend:
    build:
      context: ./reestr_back
      dockerfile: Dockerfile
    container_name: reestr_back
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    # ports:
       - "127.0.0.1:8080:8080" # Порт бэкенда
    depends_on:
      - db
    networks:
      - app-network

  # Фронтенд на Vite + Vue
  frontend:
    build:
      context: ./reestr_front
      dockerfile: Dockerfile
    container_name: reestr_front
    restart: always
    ports:
      - "127.0.0.1:3000:3000" # Порт фронтенда
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge